In [3]:
import numpy as np


In [2]:
mylist = [1,2,3]

In [13]:
np.array(mylist)

array([1, 2, 3])

In [14]:
nested_list = [[1,2],[3,4],[5,6]]
nested_list

[[1, 2], [3, 4], [5, 6]]

In [15]:
np.array(nested_list)#tabdil be 2D mikone

array([[1, 2],
       [3, 4],
       [5, 6]])

In [20]:
np.arange(0,11,2)#az 0 ta 11 be fasele 2ta 2ta

array([ 0,  2,  4,  6,  8, 10])

In [32]:

np.zeros((4,10),dtype=int)#arraye zero vali radif o sotun moshakhas
#ba entekhab noe integer

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [26]:
np.zeros(3)

array([ 0.,  0.,  0.])

In [22]:
np.ones(3)

array([ 1.,  1.,  1.])

In [31]:
np.ones((4,4))

array([[ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.]])

In [36]:
np.linspace(0,10,3) #beyne 0 ta 10 3 adad ba fasele yeksan bde
#shamele 0 va 10

array([  0.,   5.,  10.])

In [37]:
np.linspace(0,10,21)

array([  0. ,   0.5,   1. ,   1.5,   2. ,   2.5,   3. ,   3.5,   4. ,
         4.5,   5. ,   5.5,   6. ,   6.5,   7. ,   7.5,   8. ,   8.5,
         9. ,   9.5,  10. ])

In [38]:
np.eye(5) #matrix ghotri 1 ba 5 radif

array([[ 1.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  0.,  1.]])

In [40]:
np.random.rand(2)#2 ta adade random beyne 0 o 1

array([ 0.85522909,  0.29987574])

In [41]:
np.random.rand(3,4) #adade random dar 3 radif o 4 sotun
#beyne 0 ta 1

array([[ 0.6758262 ,  0.90231332,  0.1196237 ,  0.35858764],
       [ 0.34786679,  0.25170985,  0.35338672,  0.70148899],
       [ 0.45743212,  0.67362631,  0.14269249,  0.26009042]])

In [4]:
np.random.randn(5,5)#also get negative numbers
#ba center 0 va variance 1

array([[ 0.02000725, -0.39008593,  0.9139049 ,  1.93405001,  1.27178787],
       [-0.76253624, -1.09317851, -0.42964113, -0.92449654, -1.31644954],
       [ 0.25040022, -1.40922661,  0.14283813,  0.20168334,  0.22629955],
       [-0.17662062, -0.68950402,  0.8467589 , -1.21116108,  2.09523347],
       [ 0.10031244, -0.02035145, -0.48725502,  0.4462893 ,  0.00868006]])

In [5]:
np.random.randint(1,100,10)#1 ta 100 va 10 ta mide

array([19, 34, 21, 93, 61, 74,  6, 67, 56, 30])

In [6]:
np.random.randint(1,100,(2,3))

array([[61, 48, 62],
       [95, 26, 65]])

In [11]:
np.random.seed(42)#vaghti seed ro mizanim hamun adad haye random ro mide
np.random.rand(4)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

In [13]:
np.random.rand(4)#age seed nabashe ye chize jadid mide

array([0.15601864, 0.15599452, 0.05808361, 0.86617615])

In [14]:
arr = np.arange(25)

In [99]:
ranarr = np.random.randint(0,50,10)

In [18]:
arr


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [100]:
ranarr

array([27, 15, 14, 46, 43,  2, 36,  6, 20,  8])

In [20]:
arr.shape#tedad ro mide

(25,)

In [21]:
arr.reshape(5,5)#taghyire shekl mide bayad tedad element ha yeksan bashe

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [25]:
ranarr.max()#max ro mide  va mishe be jash min ham zad

43

In [27]:
ranarr.argmax()#index max ro mide be jash min ham mishe zad

7

In [29]:
ranarr.dtype

dtype('int64')

In [30]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [31]:
arr[6]

6

In [32]:
arr[1:5]

array([1, 2, 3, 4])

In [33]:
arr[0:7] = 100 #7 ta adade aval ro 100 mikone k tu list asli python nmishe
arr

array([100, 100, 100, 100, 100, 100, 100,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24])

In [34]:
arr = np.arange(0,11)

In [38]:
slice_arr = arr[0:5]# ye meghdari az array ro bar midare
slice_arr

array([0, 1, 2, 3, 4])

In [39]:
slice_arr[:] = 99
slice_arr

array([99, 99, 99, 99, 99])

In [44]:
arr#ba taghyir ruye slice, ruye arr asli ham tasir gozasht

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

In [43]:
arr_copy = arr.copy()
arr_copy[:] = 100
arr_copy #taghyirat montaghel nashod

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [45]:
arr

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

In [47]:
arr_2d = np.array([[5,10,15],[20,25,30],[35,40,45]])
arr_2d# ye arraye 2D misaze

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [48]:
arr_2d.shape

(3, 3)

In [51]:
arr_2d[-1][1] #ye elementi az array ro migire

40

In [52]:
arr_2d[:2,1:] #radife 0 o 1 va sotune 1 o 2

array([[10, 15],
       [25, 30]])

In [55]:
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [56]:
arr > 4#shart ro emal mikone

array([False, False, False, False, False,  True,  True,  True,  True,
        True,  True])

In [57]:
bool_arr = arr>4 #shart ro be ye boolean mizare ye filter dorost mishe
bool_arr

array([False, False, False, False, False,  True,  True,  True,  True,
        True,  True])

In [58]:
arr[bool_arr] #test filter

array([ 5,  6,  7,  8,  9, 10])

In [59]:
arr[arr>4] #mesle ye filter az un compare estefade mikone

array([ 5,  6,  7,  8,  9, 10])

In [63]:
arr + 5 #ye adadi ro behesh kamo ziyad mikonim


array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [64]:
arr * arr

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [65]:
arr / arr # ye error mide k adade 0/0 ro nan mizare

/usr/lib/python3/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [66]:
1 / arr # ye error mide k adadi ro taghsim bar 0 mikone vali numpy crash nmikone

/usr/lib/python3/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111,
       0.1       ])

In [67]:
np.sqrt(arr) #jazr migire

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [69]:
np.sin(arr)#sin mide

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111])

In [70]:
np.log(arr) #baz ham warning mide vase 0

/usr/lib/python3/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458,
       2.30258509])

In [71]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [74]:
arr.sum()#jam mikone hamasho

55

In [75]:
arr.mean() #average mide

5.0

In [76]:
arr.var() #variance mide

10.0

In [77]:
arr.std()

3.1622776601683795

In [91]:
arr_2d = np.arange(0,25).reshape(5,5)
arr_2d

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [92]:
arr_2d.sum(axis=0) #0 o 1 mishe gozasht ke bgim satr ha ya sotun haro jam kone

array([50, 55, 60, 65, 70])

In [94]:
arr_2d.sum(axis=1)

array([ 10,  35,  60,  85, 110])